AWSTemplateFormatVersion: '2010-09-09'
Description: sample rest app
Transform: AWS::Serverless-2016-10-31
Resources:
  siteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /app
      Description: Resolve/Store URLs
      Events:
        postUrl:
          Type: HttpApi
          Properties:
            Method: post
            Path: /
      Handler: lambda/index.handler
      Runtime: nodejs12.x
      Timeout: 10
      Role: arn:aws:iam::337039027061:role/cf-pipeline-role

  